fix: use basemaps-cli v8 for standardising workflows (#1014)
### Motivation

Basemaps CLI package `v8` was released, unfortunately there was a
container version tagging issue that caused workflows to pull the `v8`
code but using `v7` compatible commands.

```
Error: Cannot find module '/app/node_modules/@basemaps/cogify/dist/index.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Modifications

Update the version of the `basemaps-cli` package to `v8` and update
commands accordingly for imagery and elevation related workflow
templates.

### Verification

Ran standardising using `v8` of the basemaps-cli container.


![image](https://github.com/user-attachments/assets/7d9e2282-c7ee-443d-bd2a-d5030f09b179)

```
{"level":30,"time":1747094997097,"pid":28,"hostname":"es-invercargill-3dcm-dem-n9vt9-create-config-3251564569","package":{"package":"@cli-config","version":"v8.0.0","hash":"852c7c8bcbe06d065de732f23a6ebc2dd6a19cfc","buildId":"14960309046-2"},"cli":"create-config","args":{"verbose":false,"extraVerbose":false,"concurrency":25,"host":"https://basemaps.linz.govt.nz/","path":"s3://linz-workflows-scratch/2025-05/13-es-invercargill-3dcm-dem-n9vt9/flat/"},"isArgo":true,"msg":"Cli:Start"}
```